services:
  - type: web
    name: university-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_USER
        value: Abdelrhman
      - key: DB_PASSWORD
        value: 12Bode34
      - key: DB_NAME
        value: university
      - key: NODE_ENV
        value: production
